version: '3.9'

services:
  frontend:
    image: 957691576938.dkr.ecr.us-east-2.amazonaws.com/frontend-blockscout:latest
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
